from typing import TypedDict, List
from langchain_core.messages import BaseMessage

class GraphState(TypedDict):
    """
    Represents the state of our graph.
    - user_question: The natural language question from the user.
    - sql_query: The SQL query generated by the LLM.
    - query_result: The result of executing the SQL query.
    - error_message: Any error message encountered during validation or execution.
    """
    user_question: str
    sql_query: str
    query_result: List[str]
    error_message: str